data = read.table("household_power_consumption.txt",sep=";",header=TRUE)   
data = subset(data, Date %in% c("1/2/2007","2/2/2007"))
data$newtime = strptime(paste(data$Date,data$Time,sep=" ")
                        , "%e/%m/%Y %T")
data$Sub_metering_1 = as.numeric(as.character(data$Sub_metering_1))
data$Sub_metering_2 = as.numeric(as.character(data$Sub_metering_2))
data$Sub_metering_3 = as.numeric(as.character(data$Sub_metering_3))
png("plot3.png",width=1920,height=1920,res=288)
with(data,plot(newtime, Sub_metering_1,type="n"
               ,xlab="",ylab="Energy sub metering"))
lines(data$newtime,data$Sub_metering_1)
lines(data$newtime,data$Sub_metering_2,col="red")
lines(data$newtime,data$Sub_metering_3,col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
       ,col=c("black","red","blue"),lty=1)
dev.off()